### ISSUE TITLE
Q: Why no more releases on rubygems.org

### ISSUE THREAD

**Issue by dlebrun** [mainio/decidim-module-term_customizer#122]
Why is this gem not released on rubygems.org anymore? The last released version is 0.23, while there are release branches up to version 0.27 on this reprository. Unfortunately, the specificities of our client's infrastructure does not allow us to pull the code from Github, so having the gem released on rubygems.org would be really helpful.

**Comment by ahukkanen** [comment]
Hi Dominique, the GitHub branching model fits our workflows the best which is why we do not want to use the extra time for releasing the gem versions to RubyGems.

You can make a fork of the project and release it either to RubyGems yourself with a different name or host your own private gem source where you can release it with the original name with no changes to the code.

You can also contact us directly if you'd like to discuss about managed support plans to aid your workflows. This also comes with some level of support that helps fixing any bugs found in the software. You can find our contact details from our website if you'd like to discuss further about this option.

I'll close this issue for now as this relates to the hosting part of the gem.
