### ISSUE TITLE
Create branch 0.17-stable

### ISSUE THREAD

**Issue by mijailr** [mainio/decidim-module-term_customizer#19]
The latest stable version of decidim is now in 0.17, please create branch. If you need any help count on me.

**Comment by ahukkanen** [comment]
I have bumped the core and module versions to `0.17` in the master branch at c2c00e7d12cded22f8c3c09f80a5dc624c464db7.

I will create the `0.17-stable` branch once a stable release becomes available. Before the stable release, I would like to get the remaining issues resolved.

Help would be appreciated regarding #15 and #16. Please comment those issues in advance in case you start working on them, otherwise there could be duplicate work.

**Comment by ahukkanen** [comment]
There is now a stable release of the gem for Decidim v0.17:
https://rubygems.org/gems/decidim-term_customizer/versions/0.17.0

I have also created the `0.17-stable` branch to maintain a stable version against the 0.17 mainline.
