### ISSUE TITLE
Error with installation

### ISSUE THREAD

**Issue by MohammedSalahadin** [mainio/decidim-module-term_customizer#51]
After inserting  gem "decidim-term_customizer" to the Gemfile and run bundle I got the following error:
```
Bundler could not find compatible versions for gem "decidim-admin":
  In snapshot (Gemfile.lock):
    decidim-admin (= 0.23.1)

  In Gemfile:
    decidim-dev (= 0.23.1) was resolved to 0.23.1, which depends on
      decidim (= 0.23.1) was resolved to 0.23.1, which depends on
        decidim-admin (= 0.23.1)

    decidim-term_customizer was resolved to 0.16.6, which depends on
      decidim-admin (~> 0.16.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```
After running bundle update I have got the following error:
```
Bundler could not find compatible versions for gem "decidim-core":
  In Gemfile:
    decidim-navbar_links was resolved to 0.23.1, which depends on
      decidim-core (= 0.23.1)

    decidim-term_customizer was resolved to 0.16.6, which depends on
      decidim-core (~> 0.16.0)
```
Conclusion:
This model is not compatible with the released version of decidim that I'm currently using..

**Comment by ahukkanen** [comment]
This is likely because there was no published version for 0.23 at RubyGems.

There is now:
https://rubygems.org/gems/decidim-term_customizer/versions/0.23.0

For future readers, you may also want to look into installing directly from the GitHub repository if you feel comfortable fixing any issues that may arise from an unreleased version and also contributing the fixes back. Instructions are available e.g. in this comment:
https://github.com/mainio/decidim-module-term_customizer/issues/42#issuecomment-730386974

We try to keep `master` in line with the stable version and `develop` in line with the development version of the core but do not guarantee this is always the case, so please do your own research regarding this.
