### ISSUE TITLE
Option to disable term customizer when the DB is not available

### ISSUE THREAD

**Issue by carlobeltrame** [mainio/decidim-module-term_customizer#65]
We have experienced a very weird problem which occurs when a decidim instance has both the term customizer and [this other module for anonymous proposals](https://github.com/PopulateTools/decidim-module-anonymous_proposals) installed. Basically, during the build of our containerized application, at some point, `rake assets:precompile` is called and fails, because the database is not available. Below is my analysis of the reasons why:

* The anonymous proposals module internally uses the [deface](https://github.com/spree/deface) gem to override some of the decidim views.
* During an `assets:precompile`, deface also precompiles the modified views, and in doing so happens to use `String#parameterize` ([here](https://github.com/spree/deface/blob/master/lib/deface/override.rb#L46))
* `parameterize` uses `transliterate`, that uses `enforce_available_locales!`, and that in turn needs to read the available locales from `I18n`.
* `I18n` questions its backends for the available locales, and therefore asks the term customizer.
* The term customizer tries to look up the available locales in the DB, and fails because there is no DB during an asset build.

Funnily enough, I was able to work around this unfortunate chain of events by setting `I18n.enforce_available_locales = false` in application.rb. But to be honest, it would be a far superior solution, if the term customizer could somehow "deactivate itself" in case there is no DB available. As far as I can tell, this situation could come up with any other gem that uses `parameterize` or some other `I18n` function during the assets build, the only common denominators are `I18n` and the term customizer.

What do you think about this problem, and the proposed solution? Am I wrong in saying that this should be solved in the term customizer?

I can supply the stack trace in case it is of any interest.

**Comment by ahukkanen** [comment]
I think it would be a good addition in the module.

Could you provide step-by-step instructions how to replicate this issue on a fresh Decidim instance created with the default decidim application generator (e.g. by running `decidim freshapp`)? I believe the issue exists but I would just like to have a documented way to replicate the bug, so that the fix could be confirmed properly.

I tried this with the `decidim-anoymous_proposals` module and running `rake assets:precompile` or `RAILS_ENV=production rake assets:precompile` both work fine after adding the anymous proposals module + term customizer to the Gemfile. I did not run any database migrations to ensure the database is not available.

This is what I tried (with both Decidim 0.23.x and 0.24.x):

```bash
$ cd dev
$ gem install decidim -v 0.23.4
$ decidim freshapp
# ... lots of output ...
$ cd freshapp
```

Make sure before you generate the application, you are using the specified decidim version. It means that the `decidim` executable has to come from that version. If you are not sure, use `gem info decidim-generators` to find out the the path to the correct decidim generators version and then run the executable in the generator gem's `exe` directory.

After that, I added the following to the Gemfile:

```ruby
gem "decidim-term_customizer", git: "https://github.com/mainio/decidim-module-term_customizer.git", branch: "master"
gem "decidim-anonymous_proposals", git: "https://github.com/PopulateTools/decidim-module-anonymous_proposals", branch: "main"
```

And then I ran:

```bash
$ bundle
$ RAILS_ENV=production bundle exec rake assets:precompile
```

It ran successfully and generated the assets.

**Comment by ahukkanen** [comment]
@carlobeltrame I tried to debug this further without any luck. I am not able to make it break with these two modules being installed at the same time and `I18n.enforce_available_locales` set to `true`.

If you call `I18n.backend.available_locales` before the database is available, the [call in TermCustomizer](https://github.com/mainio/decidim-module-term_customizer/blob/0e823f4f768f6255de57559c618dcad784c5d655/lib/decidim/term_customizer/i18n_backend.rb#L17-L21) will fail in an `ActiveRecord::NoDatabaseError` (subclass of `ActiveRecord::NoDatabaseError`) which will be catched in the [rescue clause that returns an empty array](https://github.com/mainio/decidim-module-term_customizer/blob/0e823f4f768f6255de57559c618dcad784c5d655/lib/decidim/term_customizer/i18n_backend.rb#L20).

If you call `I18n.backend.translations` before one of these two ([1](https://github.com/mainio/decidim-module-term_customizer/blob/0e823f4f768f6255de57559c618dcad784c5d655/lib/decidim/term_customizer/engine.rb#L19), [2](https://github.com/mainio/decidim-module-term_customizer/blob/0e823f4f768f6255de57559c618dcad784c5d655/lib/decidim/term_customizer/engine.rb#L48)) notification subscriptions have run, the loader won't be available and the TermCustomizer's I18n backend will return an empty hash.

So, I don't really know how I can make it break.

**Comment by carlobeltrame** [comment]
Thanks so much for trying to debug this! I unfortunately haven't had time to properly isolate what caused the issue with us. Once I do, I will make sure to report back with more information. But for now, according to your explanation, it sounds like the term customizer already handles cases when the DB is unavailable. So until I can provide further evidence and investigate our setup further, I think we can close this issue.
